# version: 1.0.0 - HACKER STYLE

add_newline = false
continuation_prompt = "[â¤â¤](dimmed white)"

format = """$directory$fill$git_branch$git_status$cmd_duration\n$username$hostname$sudo$character"""

right_format = """
$shlvl\
$jobs\
$time\
$python\
$nodejs\
$rust\
$package\
$memory_usage\
$status
"""

[fill]
symbol = " "

[character]
success_symbol = "[â¤](bold bright-green)"
error_symbol = "[âœ—](bold red)"
vimcmd_symbol = "[â†ª](bold yellow)"
format = "$symbol "

[username]
format = "[â˜  $user]($style) "
style_user = "bold bright-yellow"
style_root = "bold bright-red"
show_always = true

[hostname]
ssh_only = false
format = "[@$hostname]($style) "
style = "dimmed white"

[sudo]
format = "[âš¡]($style)"
style = "bold bright-red"
disabled = false

[directory]
style = "bold cyan"
format = "[â–š $path]($style) "
read_only = " [LOCKED]"
truncation_length = 3
truncation_symbol = "â€¦"

[cmd_duration]
format = "[â± $duration](dimmed white) "
min_time = 500

[jobs]
symbol = "âš™ "
style = "bold white"
format = "[$symbol$number]($style) "

[time]
disabled = false
format = "[â§– $time]($style)"
time_format = "%H:%M"
style = "italic dimmed white"

[memory_usage]
format = "[MEM: $ram]($style) "
threshold = 70
style = "bold bright-purple"
disabled = false

[status]
format = "[$symbol$status]($style)"
symbol = "âœ—"
style = "bold red"
disabled = false

# â”€â”€ Git â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[git_branch]
symbol = "â­  "
format = "[$symbol$branch]($style) "
style = "bold green"

[git_status]
style = "dimmed white"
format = "([$all_status$ahead_behind]($style))"
conflicted = "âš”"
ahead = "â‡¡"
behind = "â‡£"
diverged = "â‡•"
untracked = "?"
stashed = "ğŸ’¾"
modified = "*"
staged = "+"
renamed = "Â»"
deleted = "âœ˜"

# â”€â”€ Languages â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

[python]
format = "[PY âŒ‰ $version]($style) "
style = "bold bright-yellow"
symbol = "ğŸ"
version_format = "${raw}"

[nodejs]
format = "[NODE â—« $version]($style) "
style = "bold green"
version_format = "${raw}"

[rust]
format = "[RS âŠƒ $version]($style) "
style = "bold red"
version_format = "${raw}"

[package]
format = "[ğŸ“¦ $version]($style)"
style = "dimmed white"
version_format = "${raw}"
